// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiGqEfL6zx81u3W_ez6rSoqZyxDMiOfJQ',
    appId: '1:1050622369815:web:5c43ff60fd8f0af19cbc52',
    messagingSenderId: '1050622369815',
    projectId: 'fluttermap-c62a7',
    authDomain: 'fluttermap-c62a7.firebaseapp.com',
    storageBucket: 'fluttermap-c62a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1UufECYBCUoRLI3uOwdv0BZzWYEai4qg',
    appId: '1:1050622369815:android:6063ec7db5f6e4e29cbc52',
    messagingSenderId: '1050622369815',
    projectId: 'fluttermap-c62a7',
    storageBucket: 'fluttermap-c62a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLB08vFaervCc_ATHbI4jm_25x8KGvNE8',
    appId: '1:1050622369815:ios:2d485da20d40eaab9cbc52',
    messagingSenderId: '1050622369815',
    projectId: 'fluttermap-c62a7',
    storageBucket: 'fluttermap-c62a7.appspot.com',
    iosBundleId: 'com.example.fluttermap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLB08vFaervCc_ATHbI4jm_25x8KGvNE8',
    appId: '1:1050622369815:ios:2d485da20d40eaab9cbc52',
    messagingSenderId: '1050622369815',
    projectId: 'fluttermap-c62a7',
    storageBucket: 'fluttermap-c62a7.appspot.com',
    iosBundleId: 'com.example.fluttermap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiGqEfL6zx81u3W_ez6rSoqZyxDMiOfJQ',
    appId: '1:1050622369815:web:1b10d8541a34d8ed9cbc52',
    messagingSenderId: '1050622369815',
    projectId: 'fluttermap-c62a7',
    authDomain: 'fluttermap-c62a7.firebaseapp.com',
    storageBucket: 'fluttermap-c62a7.appspot.com',
  );
}
